[variables]
NODE_ENV = 'production'
NEXT_TELEMETRY_DISABLED = '1'

[phases.install]
cmds = ['npm ci --prefer-offline --no-audit']

[phases.build]
cmds = ['npm run build']

[phases.start]
cmd = 'npm start'
